---
  
- name: Archive the directory on remote host
  ansible.builtin.archive:
    path: /var/lib/docker/volumes/nextcloud_db
    dest: "/tmp/{{ lookup('pipe', 'date +%Y%m%d') }}_backup_nextcloud_db.tar.gz"
  register: backup_script_output

- name: ensure local backup dir is present
  file:
    path: "./backup_netxcloud_db"
    state: directory
    mode: 0755
  delegate_to: localhost
  when: backup_script_output.failed == false

- name: Copy Backup archive to nfs
  command:
    cmd: "cp /tmp/{{ lookup('pipe', 'date +%Y%m%d') }}_backup_nextcloud_db.tar.gz /mnt/nextcloud"
  become: yes
  when: backup_script_output.failed == false

- name: delete all files older than 15 days
  command:
    cmd: "find /mnt/nextcloud -type f -mtime +15 -exec rm -f {} \;"
  become: yes
  when: backup_script_output.failed == false


#- name: rsync data folder to /mnt/nextcloud
#  command:
#    cmd: "rsync -a /var/lib/docker/volumes/nextcloud_nextcloud/_data/data /mnt/nextcloud_data"
#  become: yes

- name: delete backup on remote
  file:
    path: /tmp/{{ lookup('pipe', 'date +%Y%m%d') }}_backup_nextcloud_db.tar.gz"
    state: absent
  when: backup_script_output.failed == false
